import sys
from pathlib import Path

import pytest
from openpyxl import Workbook

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


@pytest.fixture
def make_xlsx(tmp_path):
    """Create a one-sheet workbook from headers + rows and return its path."""

    def _make(name, headers, rows):
        wb = Workbook()
        ws = wb.active
        ws.append(headers)
        for row in rows:
            ws.append(row)
        path = tmp_path / name
        wb.save(path)
        return path

    return _make


@pytest.fixture(scope="session")
def samples(tmp_path_factory):
    """Fresh synthetic samples generated by generate_samples.py."""
    import generate_samples

    out = tmp_path_factory.mktemp("samples")
    generate_samples.mail_merge_samples(out)
    generate_samples.scheduler_samples(out)
    generate_samples.messy_folder_samples(out)
    generate_samples.expense_samples(out)
    generate_samples.task_samples(out)
    return out
