"""Daily brief: a one-page Markdown + HTML summary of a task list for the manager.

tasks.xlsx columns: task_id, title, owner, priority (High/Medium/Low),
status (Open/In Progress/Blocked/Done), due_date, notes

Sections: Overdue, Due today, Later this week (until Sunday), Blocked.
Done tasks are counted but never listed. Items are sorted by priority, then due date.
"""

from __future__ import annotations

import html
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from .excel_utils import read_table

PRIORITY_ORDER = {"high": 0, "medium": 1, "low": 2}
DONE = {"done", "completed", "closed"}


@dataclass(frozen=True)
class Task:
    task_id: str
    title: str
    owner: str
    priority: str
    status: str
    due: date | None
    notes: str = ""

    @property
    def is_done(self) -> bool:
        return self.status.lower() in DONE

    @property
    def sort_key(self) -> tuple[int, date]:
        return PRIORITY_ORDER.get(self.priority.lower(), 3), self.due or date.max


@dataclass
class Brief:
    today: date
    overdue: list[Task] = field(default_factory=list)
    due_today: list[Task] = field(default_factory=list)
    this_week: list[Task] = field(default_factory=list)
    blocked: list[Task] = field(default_factory=list)
    open_count: int = 0
    done_count: int = 0


def _to_date(value: Any) -> date | None:
    if value is None or str(value).strip() == "":
        return None
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    return date.fromisoformat(str(value).strip()[:10])


def task_from_row(row: dict[str, Any]) -> Task:
    return Task(
        task_id=str(row.get("task_id") or "").strip(),
        title=str(row.get("title") or "").strip(),
        owner=str(row.get("owner") or "").strip(),
        priority=str(row.get("priority") or "Medium").strip().title(),
        status=str(row.get("status") or "Open").strip().title(),
        due=_to_date(row.get("due_date")),
        notes=str(row.get("notes") or "").strip(),
    )


def build_brief(tasks: list[Task], today: date) -> Brief:
    """Bucket tasks relative to ``today``. The week ends on Sunday."""
    brief = Brief(today=today)
    week_end = today + timedelta(days=6 - today.weekday())
    for t in tasks:
        if t.is_done:
            brief.done_count += 1
            continue
        brief.open_count += 1
        if t.status.lower() == "blocked":
            brief.blocked.append(t)
        if t.due is None:
            continue
        if t.due < today:
            brief.overdue.append(t)
        elif t.due == today:
            brief.due_today.append(t)
        elif t.due <= week_end:
            brief.this_week.append(t)
    for bucket in (brief.overdue, brief.due_today, brief.this_week, brief.blocked):
        bucket.sort(key=lambda t: t.sort_key)
    return brief


def _sections(brief: Brief) -> list[tuple[str, list[Task]]]:
    return [
        ("Overdue", brief.overdue),
        ("Due today", brief.due_today),
        ("Later this week", brief.this_week),
        ("Blocked", brief.blocked),
    ]


def _due_label(t: Task, today: date) -> str:
    if t.due is None:
        return "no due date"
    delta = (t.due - today).days
    if delta < 0:
        return f"{-delta} day{'s' if delta != -1 else ''} late (due {t.due:%a %d %b})"
    if delta == 0:
        return "today"
    return f"{t.due:%a %d %b}"


def to_markdown(brief: Brief, manager: str = "Manager") -> str:
    lines = [
        f"# Daily brief — {brief.today:%A, %d %B %Y}",
        "",
        f"Good morning {manager}. **{brief.open_count} open tasks** · "
        f"{len(brief.overdue)} overdue · {len(brief.due_today)} due today · "
        f"{len(brief.this_week)} later this week · {len(brief.blocked)} blocked · "
        f"{brief.done_count} done.",
    ]
    for title, tasks in _sections(brief):
        lines += ["", f"## {title} ({len(tasks)})", ""]
        if not tasks:
            lines.append("_Nothing here._")
            continue
        lines += ["| Priority | Task | Owner | Due | Notes |", "|---|---|---|---|---|"]
        for t in tasks:
            cells = [t.priority, f"{t.task_id} {t.title}".strip(), t.owner, _due_label(t, brief.today), t.notes]
            lines.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    lines += ["", "_Generated by va_toolkit · synthetic demo data_", ""]
    return "\n".join(lines)


_CSS = """
body{font-family:Segoe UI,Arial,sans-serif;max-width:860px;margin:24px auto;padding:0 16px;color:#222}
h1{color:#1F4E78;margin-bottom:4px} h2{margin-top:28px;border-bottom:2px solid #1F4E78;padding-bottom:4px}
.kpis{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}
.kpi{background:#F2F6FA;border-radius:8px;padding:10px 14px;min-width:96px}
.kpi b{display:block;font-size:22px} .kpi.alert b{color:#C00000}
table{border-collapse:collapse;width:100%} th,td{text-align:left;padding:6px 8px;border-bottom:1px solid #ddd}
th{background:#1F4E78;color:#fff} .p-High{color:#C00000;font-weight:bold} .p-Medium{color:#B07800}
.empty{color:#888;font-style:italic} footer{margin-top:32px;color:#888;font-size:12px}
"""


def to_html(brief: Brief, manager: str = "Manager") -> str:
    e = html.escape
    kpis = [
        ("Open", brief.open_count, False), ("Overdue", len(brief.overdue), bool(brief.overdue)),
        ("Due today", len(brief.due_today), False), ("This week", len(brief.this_week), False),
        ("Blocked", len(brief.blocked), bool(brief.blocked)), ("Done", brief.done_count, False),
    ]
    parts = [
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>",
        f"<title>Daily brief {brief.today:%Y-%m-%d}</title><style>{_CSS}</style></head><body>",
        f"<h1>Daily brief — {brief.today:%A, %d %B %Y}</h1><p>Good morning {e(manager)}.</p>",
        "<div class='kpis'>"
        + "".join(f"<div class='kpi{' alert' if alert else ''}'><b>{n}</b>{label}</div>" for label, n, alert in kpis)
        + "</div>",
    ]
    for title, tasks in _sections(brief):
        parts.append(f"<h2>{title} ({len(tasks)})</h2>")
        if not tasks:
            parts.append("<p class='empty'>Nothing here.</p>")
            continue
        parts.append("<table><tr><th>Priority</th><th>Task</th><th>Owner</th><th>Due</th><th>Notes</th></tr>")
        for t in tasks:
            parts.append(
                f"<tr><td class='p-{e(t.priority)}'>{e(t.priority)}</td><td>{e(t.task_id)} {e(t.title)}</td>"
                f"<td>{e(t.owner)}</td><td>{e(_due_label(t, brief.today))}</td><td>{e(t.notes)}</td></tr>"
            )
        parts.append("</table>")
    parts.append("<footer>Generated by va_toolkit · synthetic demo data</footer></body></html>\n")
    return "\n".join(parts)


def run(tasks_path: str | Path, out_dir: str | Path, today: date | None = None, manager: str = "Manager") -> Brief:
    """End-to-end: tasks.xlsx -> ``daily_brief_<date>.md`` and ``.html``."""
    today = today or date.today()
    brief = build_brief([task_from_row(r) for r in read_table(tasks_path)], today)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / f"daily_brief_{today:%Y-%m-%d}.md").write_text(to_markdown(brief, manager), encoding="utf-8")
    (out / f"daily_brief_{today:%Y-%m-%d}.html").write_text(to_html(brief, manager), encoding="utf-8")
    return brief
